'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('./infra.cjs');
const now=Date.now(),id=C.ROOT;
function fixture(){
 const p={version:1,job:'testjob123',createdAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+1800000).toISOString(),cleanupOwner:'custodian@example.invalid',approvalId:'test-only',imageId:id+'Microsoft.Compute/galleries/test/images/runner/versions/1.0.0',imageSha256:'a'.repeat(64),artifactSha256:'b'.repeat(64),publicKey:'ssh-ed25519 '+'A'.repeat(60),databaseAddresses:['10.0.2.4'],vaultAddress:'10.0.3.4',blobAddress:'10.0.3.5',secretScope:id+'Microsoft.KeyVault/vaults/testvault/secrets/migration',containerScope:id+'Microsoft.Storage/storageAccounts/teststore/blobServices/default/containers/migration',scriptUri:'https://teststore.blob.core.windows.net/migration/bootstrap-'+ 'b'.repeat(64)+'.sh',controlEgressApproved:true};
 const s={observedAt:new Date(now).toISOString(),subscription:C.SUB,group:{id:`/subscriptions/${C.SUB}/resourceGroups/${C.RG}`,location:C.REGION},vnet:{id:C.VNET,location:C.REGION,addressSpace:{addressPrefixes:['10.0.0.0/16']}},subnet:{id:C.SUBNET,addressPrefix:'10.0.0.0/24',delegations:[]},nics:[],database:{id:C.DB,location:C.REGION,version:'14',network:{publicNetworkAccess:'Disabled',delegatedSubnetResourceId:C.VNET+'/subnets/opa-api-productionDbSubnet',privateDnsZoneArmResourceId:C.DNS}},dns:{id:C.DNS},links:[{virtualNetwork:{id:C.VNET},virtualNetworkLinkState:'Completed',registrationEnabled:false}],records:[{name:'opa-api-production-server',aRecords:[{ipv4Address:'10.0.2.4'}]}],endpoints:[{privateLinkServiceId:p.secretScope.split('/secrets/')[0],groupId:'vault',status:'Approved',address:p.vaultAddress,dnsLinked:true},{privateLinkServiceId:p.containerScope.split('/blobServices/')[0],groupId:'blob',status:'Approved',address:p.blobAddress,dnsLinked:true}],vault:{id:p.secretScope.split('/secrets/')[0],properties:{enableRbacAuthorization:true,publicNetworkAccess:'Disabled'}},storage:{id:p.containerScope.split('/blobServices/')[0],publicNetworkAccess:'Disabled',allowSharedKeyAccess:false},image:{id:p.imageId,provisioningState:'Succeeded'},imageEvidence:{sha256:p.imageSha256,nodeMajor:22,platform:'linux',arch:'x64',agentReady:true,sshDisabled:true,noCredentials:true},skuAvailable:true,runCommandSupported:true,cleanupScheduled:true,resources:[{id:id+'Microsoft.Web/sites/opa-api-production'},{id:C.VNET+'/subnets/opa-api-productionAppSubnet'},{id:C.VNET+'/subnets/opa-api-productionDbSubnet'}],assignments:[],identityTransitiveGroups:[],rbacInventoryComplete:true};return {p,s};
}
test('offline preflight and ordered commands with no public IP or credentials',()=>{const {p,s}=fixture();assert.equal(C.preflight(s,p,now).status,'verified');const script=C.commands(s,p,now);assert(script.indexOf('deny-outbound')<script.indexOf('az vm create'));assert(script.includes("--public-ip-address ''"));assert(!/custom-data|secrets show|account get-access-token|DATABASE_URL|password/.test(script));assert(C.rules(p).some(r=>r.destinationAddressPrefix==='AzureCloud'));});
const cases={subscription:s=>s.subscription='wrong',group:s=>s.group.id='wrong',region:s=>s.group.location='eastus',vnet:s=>s.vnet.id='wrong',subnet:s=>s.subnet.id=C.VNET+'/subnets/opa-api-productionAppSubnet',delegation:s=>s.subnet.delegations=[{}],nsg:s=>s.subnet.networkSecurityGroup={},route:s=>s.subnet.routeTable={},nat:s=>s.subnet.natGateway={},occupants:s=>s.nics=[{id:'unrelated',ipConfigurations:[{subnet:{id:C.SUBNET}}]}],references:s=>s.subnet.ipConfigurations=[{id:'unrelated'}],endpoint:s=>s.subnet.privateEndpoints=[{}],dns:s=>s.links[0].virtualNetwork.id='wrong',record:s=>s.records[0].aRecords[0].ipv4Address='8.8.8.8',publicDatabase:s=>s.database.network.publicNetworkAccess='Enabled',vaultPublic:s=>s.vault.properties.publicNetworkAccess='Enabled',storageKeys:s=>s.storage.allowSharedKeyAccess=true,image:s=>s.imageEvidence.nodeMajor=26,sku:s=>s.skuAvailable=false,management:s=>s.runCommandSupported=false,leaseCleanup:s=>s.cleanupScheduled=false,stale:s=>s.observedAt='2020-01-01'};
for(const [name,change] of Object.entries(cases))test('preflight rejects '+name,()=>{const {p,s}=fixture();change(s);assert.throws(()=>C.preflight(s,p,now));});
test('never silently reuses existing resources',()=>{const {p,s}=fixture(),n=C.plan(p,now);s.resources.push({id:id+'Microsoft.Network/networkSecurityGroups/'+n.nsg,location:C.REGION,tags:n.tags});assert.throws(()=>C.preflight(s,p,now),/ALREADY_EXISTS/);s.resources.at(-1).tags={};assert.throws(()=>C.teardown(s,p,now),/UNEXPECTED_RESOURCE/);});
test('expired lease cleanup still requires fresh inventory',()=>{const {p,s}=fixture(),n=C.plan(p,now);s.resources.push({id:id+'Microsoft.Network/networkSecurityGroups/'+n.nsg,location:C.REGION,tags:n.tags});assert.throws(()=>C.teardown(s,p,now+7200000),/CLEANUP_INVENTORY/);s.observedAt=new Date(now+7200000).toISOString();assert(C.teardown(s,p,now+7200000).includes('az resource delete'));});
test('partial cleanup and repeat cleanup',()=>{const {p,s}=fixture(),n=C.plan(p,now);s.resources.push({id:id+'Microsoft.Network/networkSecurityGroups/'+n.nsg,location:C.REGION,tags:n.tags});const script=C.teardown(s,p,now);assert.equal((script.match(/az resource delete/g)||[]).length,1);s.resources.pop();assert(!C.teardown(s,p,now).includes('az resource delete'));assert.equal(C.gone(s,p,structuredClone(s)).status,'verified');});
test('teardown rejects unexpected RBAC',()=>{const {p,s}=fixture(),n=C.plan(p,now);s.identity={id:id+'Microsoft.ManagedIdentity/userAssignedIdentities/'+n.identity,principalId:'11111111-1111-1111-1111-111111111111'};s.assignments=[{principalId:s.identity.principalId,scope:'subscription',roleDefinitionId:'/Owner'}];assert.throws(()=>C.teardown(s,p,now),/RBAC_DRIFT/);});
test('post teardown protects production resources',()=>{const {p,s}=fixture(),before=structuredClone(s);s.database.network.publicNetworkAccess='Enabled';assert.throws(()=>C.gone(s,p,before,now),/PRODUCTION_DRIFT/);});
test('plan rejects secret and injection fields',()=>{const {p}=fixture();p.DATABASE_URL='synthetic';assert.throws(()=>C.plan(p,now),/FIELDS/);delete p.DATABASE_URL;p.cleanupOwner='$(bad)';assert.throws(()=>C.plan(p,now),/OWNER/);});
module.exports={fixture,now};
test('inventory commands contain only read-only Azure operations',()=>{const {p}=fixture();const text=require('./inventory.cjs').inventory(p);assert(!/az .* (create|update|delete|set|login|get-access-token) /.test(text));assert(!/secret show|list-keys|customData/.test(text));assert(text.includes('nic list'));assert(text.includes('--include-inherited'));});
function postFixture(){const {p,s}=fixture(),n=C.plan(p,now),ids={vm:id+'Microsoft.Compute/virtualMachines/'+n.vm,nic:id+'Microsoft.Network/networkInterfaces/'+n.nic,nsg:id+'Microsoft.Network/networkSecurityGroups/'+n.nsg,identity:id+'Microsoft.ManagedIdentity/userAssignedIdentities/'+n.identity,disk:id+'Microsoft.Compute/disks/'+n.disk};
 s.resources.push(...Object.values(ids).map(id=>({id,location:C.REGION,tags:n.tags})));
 s.vm={id:ids.vm,networkProfile:{networkInterfaces:[{id:ids.nic}]},storageProfile:{imageReference:{id:p.imageId},osDisk:{managedDisk:{id:ids.disk}},dataDisks:[]},hardwareProfile:{vmSize:'Standard_D2s_v5'},identity:{type:'UserAssigned',userAssignedIdentities:{[ids.identity]:{}}},osProfile:{linuxConfiguration:{disablePasswordAuthentication:true}},diagnosticsProfile:{bootDiagnostics:{enabled:false}}};
 s.nic={id:ids.nic,networkSecurityGroup:{id:ids.nsg},enableIPForwarding:false,ipConfigurations:[{subnet:{id:C.SUBNET},privateIPAddress:'10.0.0.4'}]};s.nics=[s.nic];
 s.nsg={securityRules:C.rules(p).map(r=>{const {name,...properties}=r;return {name,properties};})};
 s.identity={id:ids.identity,principalId:'11111111-1111-1111-1111-111111111111'};
 s.assignments=[[p.secretScope,C.roles.secret],[p.containerScope,C.roles.blob]].map(([scope,role],i)=>({scope,roleDefinitionId:'/providers/Microsoft.Authorization/roleDefinitions/'+role,principalId:s.identity.principalId,name:`00000000-0000-0000-0000-00000000000${i}`,id:scope+'/providers/Microsoft.Authorization/roleAssignments/'+`00000000-0000-0000-0000-00000000000${i}`}));
 s.guest={nodeMajor:22,platform:'linux',arch:'x64',sshDisabled:true,artifactSha256:p.artifactSha256,resourceId:ids.vm,privateAddresses:['10.0.0.4'],databaseAddresses:p.databaseAddresses,agentHealthy:true,effectiveNsgVerified:true,routesVerified:true};return {p,s};}
test('independent post-provision proof passes exact fixture',()=>{const {p,s}=postFixture();assert.equal(C.verify(s,p,now).status,'verified');});
for(const [name,change] of Object.entries({publicIP:s=>s.nic.ipConfigurations[0].publicIPAddress={id:'bad'},loadBalancer:s=>s.nic.ipConfigurations[0].loadBalancerBackendAddressPools=[{}],wrongNic:s=>s.nic.ipConfigurations[0].subnet.id='bad',rbac:s=>s.assignments[0].scope='bad',extraRbac:s=>s.assignments.push({...s.assignments[0]}),inbound:s=>s.nsg.securityRules[0].properties.access='Allow',identity:s=>s.vm.identity.type='SystemAssigned',guestDns:s=>s.guest.databaseAddresses=['8.8.8.8'],node:s=>s.guest.nodeMajor=26,lease:s=>s.resources.at(-1).tags={}}))test('post provision rejects '+name,()=>{const {p,s}=postFixture();change(s);assert.throws(()=>C.verify(s,p,now));});
