'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {execution,validateBindings,SECRET_NAMES}=require('./staging-oidc.cjs');
const sha='a'.repeat(40);
const valid=()=>({GITHUB_REPOSITORY:'Wesley055/opa-security-awareness-app',GITHUB_REF:'refs/heads/integration/institutional-security',GITHUB_EVENT_NAME:'workflow_dispatch',GITHUB_RUN_ID:'1234',GITHUB_RUN_ATTEMPT:'1',GITHUB_SHA:sha,OPA_APPROVED_SHA:sha,OPA_STAGING_MODE:'auth-only'});
test('auth-only is accepted without migration confirmation',()=>assert.equal(execution(valid()),'auth-only'));
for(const [name,patch] of [['another repository',{GITHUB_REPOSITORY:'another/repository'}],['another branch',{GITHUB_REF:'refs/heads/other'}],['push trigger',{GITHUB_EVENT_NAME:'push'}],['unreviewed SHA',{OPA_APPROVED_SHA:'b'.repeat(40)}],['missing approval SHA',{OPA_APPROVED_SHA:''}],['arbitrary mode',{OPA_STAGING_MODE:'deploy'}],['migration without confirmation',{OPA_STAGING_MODE:'migrate'}]])test('rejects '+name,()=>assert.throws(()=>execution({...valid(),...patch})));
test('migration requires exact explicit confirmation',()=>assert.equal(execution({...valid(),OPA_STAGING_MODE:'migrate',OPA_MIGRATION_CONFIRMATION:'MIGRATE_OPA_STAGING'}),'migrate'));
function policy(){const scope='/subscriptions/b79ffdb2-0cf1-4915-89b4-2b6b7cae0299/resourceGroups/rg-opa-staging';const vault='https://opa-kv-staging.vault.azure.net';const resource=(type,name,extra={})=>({environment:'staging',id:scope+'/providers/'+type+'/'+name,...extra});const p={build:sha,settings:{OPA_NOTIFICATION_MODE:'disabled',OPA_SSO_ENABLED:'false'},resources:{app:resource('Microsoft.Web/sites','opa-api-staging'),database:resource('Microsoft.DBforPostgreSQL/flexibleServers','opa-pg-staging',{host:'opa-pg-staging.postgres.database.azure.com',port:5432,database:'opa_staging',role:'opa_staging_migrations'}),redis:resource('Microsoft.Cache/redisEnterprise','opa-redis-staging',{host:'opa-redis-staging.southafricanorth.redis.azure.net',port:10000}),vault:resource('Microsoft.KeyVault/vaults','opa-kv-staging',{secretOrigin:vault}),storage:resource('Microsoft.Storage/storageAccounts','opastagingevidence',{accountName:'opastagingevidence',container:'evidence-staging'})},secrets:{}};for(const [name,value] of Object.entries(SECRET_NAMES))p.secrets[name]={environment:'staging',vaultId:p.resources.vault.id,secretId:vault+'/secrets/'+value+'/'+'1'.repeat(32),sha256:'2'.repeat(64)};return p}
test('accepts exact fixed staging bindings',()=>assert.equal(validateBindings(policy(),sha).build,sha));
for(const [name,mutate] of [['other resource group',p=>p.resources.database.id=p.resources.database.id.replace('rg-opa-staging','rg-other')],['other vault host',p=>p.secrets.DATABASE_URL.secretId=p.secrets.DATABASE_URL.secretId.replace('opa-kv-staging','other-vault')],['unversioned secret',p=>p.secrets.DATABASE_URL.secretId=p.secrets.DATABASE_URL.secretId.replace('/'+'1'.repeat(32),'')],['runtime credential substituted',p=>p.secrets.DATABASE_URL.secretId=p.secrets.DATABASE_URL.secretId.replace('database-migration','database-runtime')],['role substitution',p=>p.resources.database.role='other_role'],['notification enablement',p=>p.settings.OPA_NOTIFICATION_MODE='live'],['SSO enablement',p=>p.settings.OPA_SSO_ENABLED='true'],['missing secret',p=>delete p.secrets.PII_LOOKUP_KEY],['secret URL override',p=>p.secrets.DATABASE_URL.secretId+='?override=1']])test('rejects '+name,()=>{const p=policy();mutate(p);assert.throws(()=>validateBindings(p,sha))});